# Prometheus is an open-source systems monitoring and alerting toolkit with an active ecosystem.
global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 15s

# Rule files specifies a list of globs. Rules and alerts are read from all matching files.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A list of scrape configurations.
# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
    # scrapes the time series data exposed by the Prometheus server
  - job_name: 'prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          instance: prometheus_localhost

    # collect metrics via Node Exporter
  - job_name: 'node'
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:9100']
        labels:
          instance: node_localhost

    # collect metrics via Mysqld Exporter
  - job_name: 'mysql'
    scrape_interval: 3s
    static_configs:
      - targets: ['127.0.0.1:9104']
        labels:
          instance: db_localhost
